### ISSUE TITLE
Не работает сортировка

### ISSUE THREAD

**Issue by Antmatveev** [undfndusr/mrp#8]
Привет, установил всё по инструкции - цены стали отображаться а сортировка нет. Ничего не трогал в коде.

![image](https://github.com/undfndusr/mrp/assets/83493408/d5b8ac93-8c5e-4297-91a4-8ca7cfa42a4a)

**Comment by undfndusr** [comment]
Скрина не достаточно, скиньте ссылку на проблемную страницу и напишите версию браузера

**Comment by Antmatveev** [comment]
Везде не работает
Опера 106
Tampermonkey устанавливал с официального [магазина расширений оперы](https://addons.opera.com/ru/extensions/details/tampermonkey-beta/)
Потом установил ваш скрипт, вот так выглядит после установки
![image](https://github.com/undfndusr/mrp/assets/83493408/699403fb-d66a-4ecb-980f-7b72181e2699)
После этого цены стали отображаться, а панель нет

**Comment by undfndusr** [comment]
Проблему нашел, поправлю как будет время.
Такой косяк можно отловить, если перейти в каталог со страницы товара.
Пока можете просто обновлять страницу.

**Comment by undfndusr** [comment]
Исправлено в новой версии 2.0.4.
Обновиться можно [на странице скрипта](https://greasyfork.org/ru/scripts/483156-megamarket-real-price)

**Comment by Antmatveev** [comment]
Обновил до 2.0.4
Теперь при смене категории, каждый раз создаётся еще один экземпляр панели

![image](https://github.com/undfndusr/mrp/assets/83493408/2ab3f879-570f-4942-a2fc-5e577c44c8d2)

**Comment by undfndusr** [comment]
Поправил в 2.0.5, теперь должно быть норм
